events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name localhost;

        # Роздача завантажених зображень Nginx
        location /images/ {
            alias /app/images/;
            autoindex off;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        # 2. Роздача CSS/JS/стилів з шаблону
        location /static/ {
            alias /app/static/;
            expires 7d;
        }
        
        # Проксування решти запитів (включаючи / та /upload) на Python-бекенд
        location / {
            proxy_pass http://app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 6M;
        }
    }
}